### ISSUE TITLE
Update sendcloud-go package for compatibility with Go 1.21

### ISSUE THREAD

**Issue by lpieri** [afosto/sendcloud-go#15]
Hey team,

Noticed sendcloud-go was last tailored for Go 1.14. With Go 1.21 out, it might be worth a check and update for any compatibility quirks. Anyone else bumped into issues with the latest Go version?

Thanks for the cool work on this package! 🚀

Cheers,
Louise

**Comment by bakkerpeter** [comment]
Thanks for reaching out. Not sure what kind of issues you have bumped into? Basically this package should work just fine in Go 1.21.
